#!/usr/bin/env php
<?php

$bundle_content = '';
$ofcms = 'onefilecms4.php';

// PHP files to bundle
$src_dir = './src/';
$files = [
    'config.php',
    'misc_functions.php',
    'svg_icons.php',
    'page_functions.php',
    'js_functions.php',
    'style_functions.php',
    'main_logic.php',
    'index.php',
];

foreach($files as $file) {
    // append to the bundle
    $bundle_content .= file_get_contents($src_dir . $file);
}

$fp = fopen($ofcms, 'w');
if (!empty($fp)) {
    if (fwrite($fp, $bundle_content)) {
        echo "File bundled!\r\n";
    } else {
        die('Could not write to file.');
        exit(-1);
    }
}

exit(0);
